
MAIN =hellocv.c
prj  =cv

#バージョン2.2決め打ち
VER=240

#Linux環境向け自動設定(下のwindows版設定をコメントアウトすると有効化)
CV_ARGS =$(pkg-config --cflags --libs opencv)

#windows環境にpkg-configは標準で存在しないので、リンク指定を決め打ちする
CV_ARGS = -lopencv_core$(VER) -lopencv_imgproc$(VER) -lopencv_highgui$(VER) -lopencv_ml$(VER) -lopencv_video$(VER) -lopencv_features2d$(VER) -lopencv_calib3d$(VER) -lopencv_objdetect$(VER) -lopencv_contrib$(VER) -lopencv_legacy$(VER) -lopencv_flann$(VER)


$(prj).exe: makefile $(MAIN)
	gcc $(MAIN) -o $(prj).exe $(CV_ARGS)

run: $(prj).exe
	$(prj).exe

clean:
	rm $(prj).exe





