
#ソースファイル名
MAIN =hellocv.c
#実行ファイル名
prj  =cv


#OpenCVライブラリオプション
ifeq ($(OS),Windows_NT)
	# Windows 上で実行された
	#バージョン2.4決め打ち
	VER=240
	#windows環境にpkg-configは標準で存在しないので、リンク指定を決め打ちする
	CV_ARGS = -lopencv_core$(VER) -lopencv_imgproc$(VER) -lopencv_highgui$(VER) \
	 -lopencv_ml$(VER) -lopencv_video$(VER) -lopencv_features2d$(VER) \
	 -lopencv_calib3d$(VER) -lopencv_objdetect$(VER) -lopencv_contrib$(VER) \
	 -lopencv_legacy$(VER) -lopencv_flann$(VER)
	CONS_BAT=!cons.bat
else
	#Linux環境向け自動設定(下のwindows版設定をコメントアウトすると有効化)
	#なお、pkg-configを使うと、OpenCVのバージョンは自動設定されるので、制限されない。
	CV_ARGS =$(pkg-config --cflags --libs opencv)
endif



$(prj).exe: makefile makefile.txt $(MAIN) $(CONS_BAT)
	gcc $(MAIN) -o $(prj).exe $(CV_ARGS)

run: $(prj).exe
	$(prj).exe

clean:
	rm $(prj).exe

